name: carbon
channels:
  - conda-forge
dependencies:
  - python=3.10.5
  - click=8.0.4
  - flake8=4.0.1
  - ipykernel=6.8.0
  - spyder=5.2.2
  - pandas=1.4.3
  - pypdf2=2.9.0
  - pyqtwebengine=5.15.7
  - pip=22.1.2
  - pip:
    - pdfreader==0.1.12
    - PyPDF2==2.10.2